server {
  listen 80;
  server_name docs.gp1.loc;
  server_tokens off;
  return 308 https://docs.gp1.loc$request_uri;
}

server {
  listen 443 ssl;
  server_name docs.gp1.loc;
  server_tokens off;
  ssl_certificate /etc/nginx/tls/current/fullchain.pem;
  ssl_certificate_key /etc/nginx/tls/current/key.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_session_cache shared:TLS:10m;
  ssl_session_timeout 1d;
  ssl_session_tickets off;
  add_header Strict-Transport-Security "max-age=31536000" always;
  client_max_body_size 100M;
  root /usr/share/nginx/html;
  location /api/ {
    proxy_pass http://backend:3000;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout 180s;
    proxy_request_buffering off;
  }
  location / { try_files $uri $uri/ /index.html; }
}
